# Site settings
title: Sakiinlaq AB
 # this is the main title of your site
email: ahmed@sakiinlaq.se
description: >-
  Sakiinlaq AB erbjuder översättning mellan svenska och somaliska.
logo: "/assets/images/logo.png"
minimal_mistakes_skin: catppuccin_mocha
search: true
atom_feed: 
  hide: true

locale: sv-SE
url: "https://sakiinlaq.se"
og_image: "/assets/images/logo.png"

# Analytics
analytics:
  provider               : ""
  google:
    tracking_id          : 
    anonymize_ip         : true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.28.0
# Outputting
permalink: /:categories/:title/

#paginate: 5 # amount of posts to show
#paginate_path: /nyheter/page:num/


timezone: Europe/Stockholm 

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
# - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ahmed Abdulqaadir Sheikh"
  avatar : "https://pbs.twimg.com/profile_images/927280578692567042/BS5Ptp5a_400x400.jpg"
  bio    : "Grundare av Sakiinlaq AB <br>Tolk, översättare och förläggare"
  url    : "https://sakiinlaq.se"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sakiinlaq.se"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sakiinlaq"   

footer: {}

defaults:
# Somaliska sidor – använd main_so
  - scope:
      path: "_pages/so"
      type: pages
    values:
      nav: main_so
      locale: so-SO

# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      nav: main
  - scope:
      path: "_tjanster"
      type: tjanster
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "tjanster"
  - scope:
      path: "_adeegyada"
      type: adeegyada
    values: 
      layout: single
      author_profile: false
      locale: so-SO
      sidebar:
        nav: "adeegyada"
  - scope:
      path: "_portfolio"
      type: portfolio
    values: 
      layout: splash
      author_profile: false
      share: false

        
# collections:
collections:
  #sheekooyin:
   # output: true
    #permalink: /:collection/:path/
  tjanster: 
    output: true
    permalink: /:collection/:path/
  adeegyada:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
